### ISSUE TITLE
'zdk.objc/HelperFactory.h' file not found

### ISSUE THREAD

**Issue by AshYadav1** [ZoiPer/SDK_iOSSwiftExample#1]
When I am download a sample and run it. It shows me a "'**zdk.objc/HelperFactory.h' file not found**" error. once I comment "import <zdk.objc/HelperFactory.h>" in bridging header file, It shows me "**<zdk.objc/ZDKContext.h> file not found.**" please let me know how i can resolve these problems.
![Screen Shot 2019-08-13 at 10 29 43 AM](https://user-images.githubusercontent.com/28678312/62916301-728bb700-bdb5-11e9-9400-99824f84b1ae.png)
![Screen Shot 2019-08-13 at 10 29 52 AM](https://user-images.githubusercontent.com/28678312/62916302-728bb700-bdb5-11e9-807d-0cd2cd337f47.png)

**Comment by ZoiPer** [comment]
Hello,

The error you are receiving is thrown, because the ZDK Framework is not added to the project, or the project cannot find it. In case you still don't have the Framework, please contact us on zoiper.com for more details.

**Comment by KirillKharkovskiy** [comment]
Hello, I cloned a project for testing, but I get such an error, tell me how to solve it
![Снимок экрана 2020-06-22 в 19 36 51](https://user-images.githubusercontent.com/55654856/85312620-ba906580-b4bf-11ea-9324-246e1b230c32.png)

**Comment by navin111** [comment]
When I am download a sample and run it. It shows me a "'zdk.objc/HelperFactory.h' file not found" error. once I comment "import <zdk.objc/HelperFactory.h>" in bridging header file, It shows me "<zdk.objc/ZDKContext.h> file not found." please let me know how i can resolve these problems.

**Comment by ivangelov** [comment]
> When I am download a sample and run it. It shows me a "'zdk.objc/HelperFactory.h' file not found" error. once I comment "import <zdk.objc/HelperFactory.h>" in bridging header file, It shows me "<zdk.objc/ZDKContext.h> file not found." please let me know how i can resolve these problems.

Hello,

The error you are receiving is thrown, because the ZDK Framework is not added to the project, or the project cannot find it. In case you still don't have the Framework, please contact us on zoiper.com for more details.

Please keep in mind that the ZDK Framework is a paid SDK product that must be purchased from zoiper.com. This is a demo project to demonstrate its uses.

**Comment by fukemy** [comment]
do we must pay money for getting ZDK Framework?

**Comment by ivangelov** [comment]
> do we must pay money for getting ZDK Framework?

Yes, ZDK Framework is a paid SDK product that must be purchased from zoiper.com. This is a demo project to demonstrate its uses.

**Comment by fukemy** [comment]
i want to ask the question, the demo can not run in our side, so how did we ensure that your framework and example can run as expected?

**Comment by ivangelov** [comment]
> i want to ask the question, the demo can not run in our side, so how did we ensure that your framework and example can run as expected?

This is a demo project and it can not run without the ZDK Framework. There is simply no way to test anything without first contacting us and getting at least a test licenses for the SDK.

Please contact us on zoiper.com.

**Comment by hushmand** [comment]
> Hello, I cloned a project for testing, but I get such an error, tell me how to solve it ![Снимок экрана 2020-06-22 в 19 36 51](https://user-images.githubusercontent.com/55654856/85312620-ba906580-b4bf-11ea-9324-246e1b230c32.png)

I have this problem too
what's the solution?

**Comment by ivangelov** [comment]
@hushmand The solution is contacting us on zoiper.com and purchasing the Zoiper SDK.

As already explained several times, this project is solely for demonstration purposes of our Zoiper SDK (ZDK) framework and can not work without it.

**Comment by hushmand** [comment]
I got the sdk from Zoiper support and added the sdk to the project as per the documentation and it gives this error.

**Comment by ivangelov** [comment]
@hushmand  After extracting the sdk archive, do you see the required files in 'zdk.objc.framework/Headers/'?

**Comment by hushmand** [comment]
Yes, next to the zdk.objc file, there is a header folder

**Comment by ivangelov** [comment]
Well... the only other thing that might causes this issue is the 'zdk.objc.framework' not to be placed in the 'SDK_iOSSwiftExample' root directory (as 'project/SDK_iOSSwiftExample/zdk.objc.framework') next to 'ZDKDemo', 'ZDKDemo.xcodeproj', etc...

**Comment by GovardhanReddy-P10** [comment]
Hi
I have added SDK in the sample application, When I am trying to build the app then getting this error
**error build: Undefined symbol: _OBJC_CLASS_$_HelperFactory**
![Screen Shot 2023-03-11 at 11 38 29 AM](https://user-images.githubusercontent.com/63334091/224468299-e0d9af06-d8e1-4bdc-a344-934a8f746b5a.png)
 please help me to resolve this

**Comment by ivangelov** [comment]
@GovardhanReddy-P10  please contact your sales representative who gave you the download links for the SDK framework and provided you with test licenses.
