### ISSUE TITLE
Linked against modern SDK, VOIP socket will not wake.

### ISSUE THREAD

**Issue by hushmand** [ZoiPer/SDK_iOSSwiftExample#2]
When I run the app(Xcode14, iOS 16) and register, it shows this error:
Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead
I used Zoiper iOS demo app.

<img width="1170" alt="Screen Shot 2022-10-15 at 3 58 33 AM" src="https://user-images.githubusercontent.com/14809049/195974078-90dce09c-c8fc-4f56-b6dd-e9ce5f1e272e.png">

In the previous version of the Xcode & iOS, this problem did not exist, and after the update, this problem occurred

**Comment by ivangelov** [comment]
Yes, it is a known issue with Xcode 14. Please contact us over your support channel with us and you will receive un an ETA for the next SDK release, where the issue is fixed, along with a workaround so you can continue your work until than.

**Comment by hushmand** [comment]
Is there a temporary way other than downgrading to the Xcode13?
